"""
phase5_langchain_chatbot.py
============================
AI-powered chatbot using LangChain + Groq that answers
questions about your NIFTY 50 trading signals.

The AI knows:
  - Latest BUY/HOLD/SELL signal for each stock
  - Confidence scores
  - SHAP feature drivers
  - Backtest performance

Get your FREE Groq API key at: https://console.groq.com
Then create a .env file with: GROQ_API_KEY=your_key_here
"""

import os
import pandas as pd
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain.schema import SystemMessage, HumanMessage, AIMessage

load_dotenv()

# ──────────────────────────────────────────
# CONFIG
# ──────────────────────────────────────────
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
MODEL_NAME   = "llama-3.3-70b-versatile"    # fast, free Groq model
SNAPSHOT_PATH = "outputs/signal_snapshot.csv"


# ──────────────────────────────────────────
# LOAD SIGNAL DATA
# ──────────────────────────────────────────
def load_signal_data() -> str:
    """
    Loads the signal snapshot CSV and formats it as
    a readable string to inject into the AI's context.
    """
    if not os.path.exists(SNAPSHOT_PATH):
        return "Signal data not available. Please run phase4_ensemble_shap.py first."

    df = pd.read_csv(SNAPSHOT_PATH)

    lines = ["CURRENT NIFTY 50 TRADING SIGNALS (Generated by ML Model)\n"]
    lines.append(f"{'='*60}")

    for _, row in df.iterrows():
        lines.append(f"""
Stock     : {row['Ticker']}
Signal    : {row['Signal']}
Confidence: {row['Confidence']}
Top Feature Drivers (SHAP):
  1. {row['Top_Feature_1']}
  2. {row['Top_Feature_2']}
  3. {row['Top_Feature_3']}
Backtest Performance:
  Strategy Return : {row['Strategy_Return']}
  Buy & Hold      : {row['BH_Return']}
  Sharpe Ratio    : {row['Sharpe']}
  Win Rate        : {row['Win_Rate']}
{'-'*40}""")

    return "\n".join(lines)


# ──────────────────────────────────────────
# SYSTEM PROMPT
# ──────────────────────────────────────────
def build_system_prompt(signal_data: str) -> str:
    return f"""You are an AI-powered trading signal analyst for NIFTY 50 Indian stocks.
You have been built using an ensemble of XGBoost and LSTM machine learning models
trained on 6 years of real NSE historical data (2015-2021).

You help users understand trading signals generated by the ML model.

IMPORTANT RULES:
1. You ONLY provide decision support — NOT financial advice
2. Always mention the confidence score when discussing a signal
3. Explain SHAP drivers in simple terms when asked why
4. Always remind users that past performance does not guarantee future returns
5. Be concise, clear, and professional
6. If asked about a stock not in the data, say it is not currently tracked

Here is the latest signal data from the ML model:

{signal_data}

Use this data to answer all questions accurately.
"""


# ──────────────────────────────────────────
# CHATBOT CLASS
# ──────────────────────────────────────────
class TradingChatbot:
    def __init__(self):
        if not GROQ_API_KEY:
            raise ValueError(
                "GROQ_API_KEY not found!\n"
                "1. Go to https://console.groq.com and get a free API key\n"
                "2. Create a .env file in this folder\n"
                "3. Add this line: GROQ_API_KEY=your_key_here"
            )

        self.llm = ChatGroq(
            groq_api_key = GROQ_API_KEY,
            model_name   = MODEL_NAME,
            temperature  = 0.3,      # lower = more factual, less creative
            max_tokens   = 1024,
        )

        self.signal_data    = load_signal_data()
        self.system_prompt  = build_system_prompt(self.signal_data)
        self.chat_history   = []

        print("\n" + "="*60)
        print("  📈 NIFTY 50 AI Trading Signal Chatbot")
        print("  Powered by LangChain + Groq (LLaMA 3)")
        print("="*60)
        print("  Type your question below. Type 'quit' to exit.")
        print("  Type 'signals' to see all current signals.")
        print("="*60 + "\n")

    def chat(self, user_input: str) -> str:
        # Shortcut command
        if user_input.lower() == "signals":
            return self.signal_data

        # Build message list: system + history + new message
        messages = [SystemMessage(content=self.system_prompt)]
        for msg in self.chat_history:
            messages.append(msg)
        messages.append(HumanMessage(content=user_input))

        # Call Groq via LangChain
        response = self.llm.invoke(messages)
        ai_reply = response.content

        # Save to history (keeps context across turns)
        self.chat_history.append(HumanMessage(content=user_input))
        self.chat_history.append(AIMessage(content=ai_reply))

        # Keep only last 10 messages to avoid token limit
        if len(self.chat_history) > 10:
            self.chat_history = self.chat_history[-10:]

        return ai_reply

    def run(self):
        """Main chat loop"""
        while True:
            try:
                user_input = input("You: ").strip()

                if not user_input:
                    continue
                if user_input.lower() in ["quit", "exit", "bye"]:
                    print("\nAI: Goodbye! Remember — this is decision support, not financial advice. 📊")
                    break

                print("\nAI: ", end="", flush=True)
                response = self.chat(user_input)
                print(response)
                print()

            except KeyboardInterrupt:
                print("\n\nExiting chatbot...")
                break
            except Exception as e:
                print(f"\nError: {e}\n")


# ──────────────────────────────────────────
# EXAMPLE QUESTIONS (for demo)
# ──────────────────────────────────────────
EXAMPLE_QUESTIONS = [
    "Which stocks have a BUY signal right now?",
    "Why is the model saying SELL for SBIN?",
    "Which stock has the highest confidence signal?",
    "Should I invest in RELIANCE based on the model?",
    "Explain the SHAP drivers for INFY in simple words",
    "Which stocks beat the buy and hold strategy?",
    "What is the Sharpe ratio and which stock has the best one?",
    "Compare RELIANCE and TCS signals",
]


if __name__ == "__main__":
    print("\n💡 Example questions you can ask:")
    for i, q in enumerate(EXAMPLE_QUESTIONS, 1):
        print(f"   {i}. {q}")

    bot = TradingChatbot()
    bot.run()
