name: ML Pipeline CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r files/requirements.txt

    - name: Run Phase 1
      run: python files/phase1_data_pipeline.py

    - name: Run Phase 2
      run: python files/phase2_labels.py

    - name: Check outputs
      run: |
        ls outputs